---
- name: Install Dependencies on the DO Droplets
  hosts: servers

  tasks:
    - name: Update apt cache and install dependencies
      become: true
      ansible.builtin.apt:
        name: '{{ packages }}'
        state: present
        update_cache: true
      vars:
        packages:
          - curl
          - git
          - ca-certificates
          - apt-transport-https
          - software-properties-common
          - python3
          - python3-pip
          - python3-setuptools
          - python3-venv
          - virtualenv

    - name: Add Docker GPG key
      become: true
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      when: ansible_distribution == "Debian"
      register: docker_gpg

    - name: Add Docker Repository
      become: true
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present
      when: ansible_distribution == "Debian" and docker_gpg.changed
      register: docker_repo

    - name: Install Docker
      become: true
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true
      # when: docker_repo.changed
      register: docker_install

    - name: Ensure Docker is running
      become: true
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      # when: docker_install.changed
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
