---
- name: Deploy Program Files to the DO Droplets
  hosts: droplets

  tasks:
    - name: Copy the program files & scripts to the droplets
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /app/
        mode: "0644"
      with_fileglob:
        - ./../../webhook/webhook_listener.py
        - ./../../scripts/Makefile

    - name: Copy service files to the droplets
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/systemd/system/
        mode: "0644
      with_fileglob:
        - ./../../scripts/webhook-listener.service