webhook_enable:
	systemctl enable webhook-listener.service

webhook_disable:
	systemctl disable webhook-listener.service

webhook_start:
	systemctl start webhook-listener.service

webhook_stop:
	systemctl stop webhook-listener.service
