name: CD

on:
  push:
    branches: [ 'main', 'dev' ]

jobs:
  server_test:
    defaults:
      run:
        working-directory: ./server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Run tests
        run: go test -v ./...

  server_build-docker-image:
    defaults:
      run:
        working-directory: ./server
    needs: server_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag tchat/api:latest

      - name: Log into the Vultr Container Registry
        run: docker login https://sjc.vultrcr.com/xtasnim  -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push the Docker image
        run: |
          docker tag tchat/api:latest sjc.vultrcr.com/xtasnim/tchat-api:latest
          docker push sjc.vultrcr.com/xtasnim/tchat-api:latest
