name: Client Release

on:
  push:
    branches: ['temp']

jobs:
  client_release:
    defaults:
      run:
        working-directory: ./client
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod download -x

      - name: Build client
        env:
          CGO_ENABLED: 1
          GOOS: darwin
          GOARCH: arm64
        run: go build -o /tmp/dist/client
      
      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: /tmp/dist/client
