name: Client Release

on:
  push:
    branches: ['temp']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest]  
        arch: [amd64, arm64] 
        exclude:
          - os: macos-12
            arch: amd64

    defaults:
      run:
        working-directory: ./client 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod download -x

      - name: test
        run: go test -v ./...

      - name: Build client
        env:
          CGO_ENABLED: 1
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: go build -o client

      - name: Upload client artifact
        uses: actions/upload-artifact@v3
        with:
          name: tchat-${{ matrix.os }}-${{ matrix.arch }} 
          path: ./client 
